// /src/services/DataExamples/sedesResponse.js

export const sedesResponses = [
  {
    id: "18",
    codigo: 1,
    nombre: "Sede Central",
    tipo: "PRINCIPAL",
    estado: "ACTIVA",
    jornada: "ambas",
    schoolId: "SCH-0001",
    school: {
      id: "SCH-0001",
      nombre: "Institución Educativa Proyecto B",
      nit: "900123456-7",
    },
    direccion: {
      pais: "Colombia",
      departamento: "Antioquia",
      ciudad: "Medellín",
      barrio: "Laureles",
      via: "Calle 44",
      numero: "75-21",
      complemento: "Bloque A",
      codigoPostal: "050031",
      referencia: "Frente al parque principal",
      lat: 6.244203,
      lng: -75.581212,
    },
    contacto: {
      telefono: "+57 604 444 1234",
      celular: "+57 300 123 4567",
      email: "sede.central@proyectob.edu.co",
    },
  },
  {
    id: "18",
    codigo: 2,
    nombre: "Sede Norte",
    tipo: "SATELITE",
    estado: "ACTIVA",
    jornada: "mañana",
    schoolId: "SCH-0001",
    school: {
      id: "SCH-0001",
      nombre: "Institución Educativa Proyecto B",
      nit: "900123456-7",
    },
    direccion: {
      pais: "Colombia",
      departamento: "Antioquia",
      ciudad: "Medellín",
      barrio: "Castilla",
      via: "Carrera 65",
      numero: "98-10",
      complemento: "Piso 2",
      codigoPostal: "050034",
      referencia: "Cerca a la estación",
      lat: 6.287512,
      lng: -75.570219,
    },
    contacto: {
      telefono: "+57 604 444 2233",
      celular: "+57 300 222 3344",
      email: "sede.norte@proyectob.edu.co",
    },
  },
  {
    id: "18",
    codigo: 3,
    nombre: "Sede Sur",
    tipo: "SATELITE",
    estado: "INACTIVA",
    jornada: "tarde",
    schoolId: "SCH-0001",
    school: {
      id: "SCH-0001",
      nombre: "Institución Educativa Proyecto B",
      nit: "900123456-7",
    },
    direccion: {
      pais: "Colombia",
      departamento: "Antioquia",
      ciudad: "Itagüí",
      barrio: "Santa María",
      via: "Avenida 42",
      numero: "15-08",
      complemento: "Bloque C",
      codigoPostal: "055410",
      referencia: "Diagonal al centro comercial",
      lat: 6.171941,
      lng: -75.611255,
    },
    contacto: {
      telefono: "+57 604 444 3344",
      celular: "+57 300 444 5566",
      email: "sede.sur@proyectob.edu.co",
    },
  },
];
